### ISSUE TITLE
using materializecss with bootstrap?

### ISSUE THREAD

**Issue by flieks** [CharlesPockert/aurelia-bs-grid#25]
i'm using dogfalo/materialize but had problems before utilizing the 2 frameworks.
problably css classes that have the same names.

question would be:
can i inject the materlialize css classes in your source code without changing your code in some way..

materlialize uses:

```
<div class="row" >
      <div class="col m6 s12 ">
```

**Comment by charlespockert** [comment]
I don't think there's any reason why anyone would need to be constrained - since it's based on tables/inputs and nothing special there should be a way to support CSS frameworks without coupling to bootstrap.

When 0.0.2 is out I'll look at maybe forking to a non-bs repo and see how easy it is to get it working - are you ideally wanting to use dogfalo/materialize without bootstrap?

**Comment by charlespockert** [comment]
At the moment the grid uses tables, but I plan to add table-less support (using divs/whatever you want) which is #6

Since attributes are forwarded to your "row" and "cell" containers you can style however you like - so yes this will be supported at some point. It's on the roadmap for v0.0.3

**Comment by charlespockert** [comment]
You can still inject classes into the `<tr>` and `<td>` by putting `class` on `<grid-row>` and `<grid-col>` if tables will work for dogfalo/materialize

**Comment by flieks** [comment]
thanks,
i read that using the 2 frameworks is not a good idea (overlapping classes)
so i will wait for 0.3.0 so that i don't have to use bootstrap
