### ISSUE TITLE
Issue in promises while using grid

### ISSUE THREAD

**Issue by Santosh-9890** [CharlesPockert/aurelia-bs-grid#60]
Hello Charles,

Have a look at below given issue,

![image](https://cloud.githubusercontent.com/assets/11840497/10040214/44852f12-61f7-11e5-842e-5bac746fb7b3.png)

Kindly revert for further clarifications and queries.

Regards,
Santosh

**Comment by charlespockert** [comment]
Hi Santosh, this is due to the grid not working with the latest version of Aurelia, new release just out here: https://github.com/CharlesPockert/aurelia-bs-grid/releases/tag/0.0.3

**Comment by Santosh-9890** [comment]
No I tried this too, still not working.
getting same error.
Do me a favor test it and then release it.

**Comment by charlespockert** [comment]
Hi @Santosh-9890, I have tested, works fine with the latest version of skeleton-navigation

Are you sure you are installing the latest release `0.0.3` and using the latest version of the Aurelia libs?

In your screenshot it looks like you are running an older version of Aurelia - the APIs have changed since and the configuration object no longer uses the `globalizeResources` method which is probably why you are getting the error

I cloned a fresh skeleton-navigation repo and installed the plugin and got the following:

![image](https://cloud.githubusercontent.com/assets/9073518/10058892/b473aeb4-623f-11e5-9d2d-ee1f8693bee4.png)

**Comment by Santosh-9890** [comment]
Hi Charles,
   Thanks for pointing out in the right direction. I have done the changes as told and the error with global resources is no longer there. But now it says that I need a file

"jspm_packages/github/CharlesPockert/aurelia-compiler@0.0.7.js"

I searched for the same in the folder aurelia-bs-grid-0.0.3 that you had provided but could not locate the same. Can you please help me with this. Its a bit urgent. Attaching screenshot

![image](https://cloud.githubusercontent.com/assets/11840497/10071491/e34855da-62d7-11e5-8e89-6cd2cd9d0f6c.png)

**Comment by charlespockert** [comment]
Hi @Santosh-9890 I've just fixed this and re-released v0.0.3 - the issue was with my github username and the fact that some users were installing with a lower-case syntax 

e.g. 

`jspm install github:charlespockert/aurelia-bs-grid`

vs

`jspm install github:CharlesPockert/aurelia-bs-grid`

As this is causing many issues, I've changed my username to lower case. If you uninstall the grid and compiler and re-install it, (ensuring you are using lower-case), it should resolve the issue, but please note, I'm not able to check it thoroughly at the moment

**Comment by charlespockert** [comment]
You may also require the systemjs css plugin which can be installed using the following jspm command:

`jspm install css=github:systemjs/plugin-css`

It needs to be aliased as `css` to work correctly with Aurelia

**Comment by charlespockert** [comment]
I've updated to release 0.0.4 because the jspm cache was causing people issues with the mixed case
